"""empty message

Revision ID: f527d49ad7db
Revises: 
Create Date: 2024-05-17 21:34:36.661245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f527d49ad7db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'company',
        sa.Column('status', sa.String(length=256), nullable=False),
        sa.Column('description', sa.String(length=256), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'order',
        sa.Column('description', sa.String(length=512), nullable=True),
        sa.Column(
            'status', sa.Enum('NEW', 'PROCESSING', 'DELIVERED', 'FINISHED', 'CANCELLED', name='orderstatus'),
            nullable=False
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'order_customer',
        sa.Column('first_name', sa.String(length=32), nullable=True),
        sa.Column('second_name', sa.String(length=32), nullable=True),
        sa.Column('phone_number', sa.String(length=16), nullable=False),
        sa.Column('email', sa.String(length=128), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['order_id'], ['order.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_customer_order_id'), 'order_customer', ['order_id'], unique=False)
    op.create_table(
        'order_item',
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('title', sa.String(length=256), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('currency', sa.String(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['order_id'], ['order.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.create_table(
        'order_shipping',
        sa.Column('country', sa.String(length=128), nullable=False),
        sa.Column('city', sa.String(length=128), nullable=False),
        sa.Column('post_code', sa.String(length=128), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['order_id'], ['order.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_shipping_order_id'), 'order_shipping', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_shipping_order_id'), table_name='order_shipping')
    op.drop_table('order_shipping')
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_order_customer_order_id'), table_name='order_customer')
    op.drop_table('order_customer')
    op.drop_table('order')
    op.drop_table('company')
    # ### end Alembic commands ###
